on:
  push:
    branches:
      - master

name: CI

jobs:
  pipeline:
    env:
      FORM3_ACCOUNT_API_URL: 'http://accountapi:8080'
    strategy:
      matrix:
        go-version: [1.20.x]
        platform: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.platform }}

    steps:

    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Tidy
      shell: bash
      run: |
          go mod tidy
          STATUS=$(git status --porcelain go.mod go.sum)
          if [ ! -z "$STATUS" ]; then
            exit 1
          fi

    - name: Test
      run: go test -race -shuffle=on -parallel 16 -v ./... -tags=unit