on:
  push:
    branches:
      - master

name: CI

jobs:
  pipeline:
    env:
      FORM3_ACCOUNT_API_URL: 'http://accountapi:8080'
    strategy:
      matrix:
        go-version: [1.20.x]
        platform: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.platform }}

    steps:

    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout
      uses: actions/checkout@v3

    - name: Tidy
      shell: bash
      run: |
          go mod tidy
          STATUS=$(git status --porcelain go.mod go.sum)
          if [ ! -z "$STATUS" ]; then
            echo "not ok"
            exit 1
          else
            echo "ok"
          fi

    - name: Format
      shell: bash
      run: |
          if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
            echo "not ok"
            exit 1
          else
            echo "ok"
          fi

    - name: Lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.52.2

    - name: Test
      run: go test -race -shuffle=on -parallel 16 -v ./... -tags=unit