on:
  push:
    branches:
      - master

name: CI

jobs:
  pipeline:
    env:
      FORM3_ACCOUNT_API_URL: 'http://localhost:8080'
      TEST_DATABASE_HOST: 'localhost'
      TEST_DATABASE_USERNAME: 'interview_accountapi_user'
      TEST_DATABASE_PASSWORD: '123'
      TEST_DATABASE_NAME: 'interview_accountapi'
      TEST_DATABASE_PORT: '5432'
      TEST_DATABASE_SSL_MODE: 'disable'
    strategy:
      matrix:
        go-version: [1.20.x]
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:

    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout
      uses: actions/checkout@v3

    - name: Docker Compose
      uses: isbang/compose-action@v1.4.1
      with:
        services: |
          accountapi

    - name: Tidy
      shell: bash
      run: |
          go mod tidy
          STATUS=$(git status --porcelain go.mod go.sum)
          if [ ! -z "$STATUS" ]; then
            echo "not ok"
            exit 1
          else
            echo "ok"
          fi

    - name: Format
      shell: bash
      run: |
          if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
            echo "not ok"
            exit 1
          else
            echo "ok"
          fi

    - name: Lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.52.2

    - name: Unit Test
      run: go test -race -shuffle=on -parallel 16 -v ./... -tags=unit

    - name: Integration Test
      run: go test -race -shuffle=on -parallel 16 -v ./... -tags=integration